p8105\_hw2\_dk2759
================
Darwin Keung
10/4/2018

## Problem 1: NYC Subway Data

Importing Data

``` r
options(tibble.print_min = 5)

NYC_Subway_Data = read_csv(file = "./Data/NYC_Transit_Subway_Entrance_And_Exit_Data.csv")
```

    ## Parsed with column specification:
    ## cols(
    ##   .default = col_character(),
    ##   `Station Latitude` = col_double(),
    ##   `Station Longitude` = col_double(),
    ##   Route8 = col_integer(),
    ##   Route9 = col_integer(),
    ##   Route10 = col_integer(),
    ##   Route11 = col_integer(),
    ##   ADA = col_logical(),
    ##   `Free Crossover` = col_logical(),
    ##   `Entrance Latitude` = col_double(),
    ##   `Entrance Longitude` = col_double()
    ## )

    ## See spec(...) for full column specifications.

``` r
names(NYC_Subway_Data)
```

    ##  [1] "Division"           "Line"               "Station Name"      
    ##  [4] "Station Latitude"   "Station Longitude"  "Route1"            
    ##  [7] "Route2"             "Route3"             "Route4"            
    ## [10] "Route5"             "Route6"             "Route7"            
    ## [13] "Route8"             "Route9"             "Route10"           
    ## [16] "Route11"            "Entrance Type"      "Entry"             
    ## [19] "Exit Only"          "Vending"            "Staffing"          
    ## [22] "Staff Hours"        "ADA"                "ADA Notes"         
    ## [25] "Free Crossover"     "North South Street" "East West Street"  
    ## [28] "Corner"             "Entrance Latitude"  "Entrance Longitude"
    ## [31] "Station Location"   "Entrance Location"

``` r
NYC_Subway_Data = janitor::clean_names(NYC_Subway_Data)
names(NYC_Subway_Data)
```

    ##  [1] "division"           "line"               "station_name"      
    ##  [4] "station_latitude"   "station_longitude"  "route1"            
    ##  [7] "route2"             "route3"             "route4"            
    ## [10] "route5"             "route6"             "route7"            
    ## [13] "route8"             "route9"             "route10"           
    ## [16] "route11"            "entrance_type"      "entry"             
    ## [19] "exit_only"          "vending"            "staffing"          
    ## [22] "staff_hours"        "ada"                "ada_notes"         
    ## [25] "free_crossover"     "north_south_street" "east_west_street"  
    ## [28] "corner"             "entrance_latitude"  "entrance_longitude"
    ## [31] "station_location"   "entrance_location"

``` r
## visual check of the data
NYC_Subway_Data
```

    ## # A tibble: 1,868 x 32
    ##   division line  station_name station_latitude station_longitu… route1
    ##   <chr>    <chr> <chr>                   <dbl>            <dbl> <chr> 
    ## 1 BMT      4 Av… 25th St                  40.7            -74.0 R     
    ## 2 BMT      4 Av… 25th St                  40.7            -74.0 R     
    ## 3 BMT      4 Av… 36th St                  40.7            -74.0 N     
    ## 4 BMT      4 Av… 36th St                  40.7            -74.0 N     
    ## 5 BMT      4 Av… 36th St                  40.7            -74.0 N     
    ## # ... with 1,863 more rows, and 26 more variables: route2 <chr>,
    ## #   route3 <chr>, route4 <chr>, route5 <chr>, route6 <chr>, route7 <chr>,
    ## #   route8 <int>, route9 <int>, route10 <int>, route11 <int>,
    ## #   entrance_type <chr>, entry <chr>, exit_only <chr>, vending <chr>,
    ## #   staffing <chr>, staff_hours <chr>, ada <lgl>, ada_notes <chr>,
    ## #   free_crossover <lgl>, north_south_street <chr>,
    ## #   east_west_street <chr>, corner <chr>, entrance_latitude <dbl>,
    ## #   entrance_longitude <dbl>, station_location <chr>,
    ## #   entrance_location <chr>

``` r
skimr::skim(NYC_Subway_Data)
```

    ## Skim summary statistics
    ##  n obs: 1868 
    ##  n variables: 32 
    ## 
    ## ── Variable type:character ──────────────────────────────────────────────────────────────
    ##            variable missing complete    n min max empty n_unique
    ##           ada_notes    1793       75 1868   5  17     0       10
    ##              corner      32     1836 1868   1   4     0        8
    ##            division       0     1868 1868   3   3     0        3
    ##    east_west_street      35     1833 1868   6  24     0      352
    ##   entrance_location       0     1868 1868  22  23     0     1857
    ##       entrance_type       0     1868 1868   4   9     0        7
    ##               entry       0     1868 1868   2   3     0        2
    ##           exit_only    1812       56 1868   3   3     0        1
    ##                line       0     1868 1868   5  17     0       36
    ##  north_south_street      29     1839 1868   4  23     0      307
    ##              route1       0     1868 1868   1   2     0       24
    ##              route2     848     1020 1868   1   2     0       20
    ##              route3    1374      494 1868   1   2     0       18
    ##              route4    1547      321 1868   1   1     0       13
    ##              route5    1630      238 1868   1   1     0       12
    ##              route6    1741      127 1868   1   1     0        7
    ##              route7    1788       80 1868   1   2     0        7
    ##         staff_hours    1828       40 1868  16  33     0       16
    ##            staffing       0     1868 1868   4   6     0        4
    ##    station_location       0     1868 1868  20  23     0      472
    ##        station_name       0     1868 1868   4  39     0      356
    ##             vending       0     1868 1868   2   3     0        2
    ## 
    ## ── Variable type:integer ────────────────────────────────────────────────────────────────
    ##  variable missing complete    n mean   sd p0 p25 p50 p75 p100     hist
    ##   route10    1845       23 1868 3    0     3   3   3   3    3 ▁▁▁▇▁▁▁▁
    ##   route11    1845       23 1868 7    0     7   7   7   7    7 ▁▁▁▇▁▁▁▁
    ##    route8    1820       48 1868 2.98 1.94  1   1   4   5    5 ▇▁▁▁▁▂▁▇
    ##    route9    1840       28 1868 2.54 1.17  2   2   2   2    5 ▇▁▁▁▁▁▁▂
    ## 
    ## ── Variable type:logical ────────────────────────────────────────────────────────────────
    ##        variable missing complete    n mean                      count
    ##             ada       0     1868 1868 0.25 FAL: 1400, TRU: 468, NA: 0
    ##  free_crossover       0     1868 1868 0.78 TRU: 1448, FAL: 420, NA: 0
    ## 
    ## ── Variable type:numeric ────────────────────────────────────────────────────────────────
    ##            variable missing complete    n   mean    sd     p0    p25
    ##   entrance_latitude       0     1868 1868  40.73 0.07   40.58  40.69
    ##  entrance_longitude       0     1868 1868 -73.86 3.42  -74.03 -73.99
    ##    station_latitude       0     1868 1868  40.73 0.07   40.58  40.69
    ##   station_longitude       0     1868 1868 -73.94 0.057 -74.03 -73.99
    ##     p50    p75   p100     hist
    ##   40.73  40.77  40.9  ▂▂▅▇▇▂▃▂
    ##  -73.96 -73.91  73.99 ▇▁▁▁▁▁▁▁
    ##   40.73  40.77  40.9  ▂▂▅▇▇▂▃▂
    ##  -73.96 -73.91 -73.76 ▃▇▅▃▂▁▁▁

Cleaning the data; retain line, station, name, station latitude /
longitude, routes served, entry, vending, entrance type, and ADA
compliance

``` r
select(NYC_Subway_Data, line, station_name, station_latitude, station_longitude, route1, route2, route3, route4, route5, route6, route7, route8, route9, route10, route11, entrance_type, entry, vending, ada)
```

    ## # A tibble: 1,868 x 19
    ##   line  station_name station_latitude station_longitu… route1 route2 route3
    ##   <chr> <chr>                   <dbl>            <dbl> <chr>  <chr>  <chr> 
    ## 1 4 Av… 25th St                  40.7            -74.0 R      <NA>   <NA>  
    ## 2 4 Av… 25th St                  40.7            -74.0 R      <NA>   <NA>  
    ## 3 4 Av… 36th St                  40.7            -74.0 N      R      <NA>  
    ## 4 4 Av… 36th St                  40.7            -74.0 N      R      <NA>  
    ## 5 4 Av… 36th St                  40.7            -74.0 N      R      <NA>  
    ## # ... with 1,863 more rows, and 12 more variables: route4 <chr>,
    ## #   route5 <chr>, route6 <chr>, route7 <chr>, route8 <int>, route9 <int>,
    ## #   route10 <int>, route11 <int>, entrance_type <chr>, entry <chr>,
    ## #   vending <chr>, ada <lgl>

Convert the entry variable from character (YES vs NO) to a logical
variable

``` r
NYC_Subway_Data$entry <- as.logical(recode(NYC_Subway_Data$entry, "YES" = "TRUE", "NO" = "FALSE"))
skimr::skim(NYC_Subway_Data)
```

    ## Skim summary statistics
    ##  n obs: 1868 
    ##  n variables: 32 
    ## 
    ## ── Variable type:character ──────────────────────────────────────────────────────────────
    ##            variable missing complete    n min max empty n_unique
    ##           ada_notes    1793       75 1868   5  17     0       10
    ##              corner      32     1836 1868   1   4     0        8
    ##            division       0     1868 1868   3   3     0        3
    ##    east_west_street      35     1833 1868   6  24     0      352
    ##   entrance_location       0     1868 1868  22  23     0     1857
    ##       entrance_type       0     1868 1868   4   9     0        7
    ##           exit_only    1812       56 1868   3   3     0        1
    ##                line       0     1868 1868   5  17     0       36
    ##  north_south_street      29     1839 1868   4  23     0      307
    ##              route1       0     1868 1868   1   2     0       24
    ##              route2     848     1020 1868   1   2     0       20
    ##              route3    1374      494 1868   1   2     0       18
    ##              route4    1547      321 1868   1   1     0       13
    ##              route5    1630      238 1868   1   1     0       12
    ##              route6    1741      127 1868   1   1     0        7
    ##              route7    1788       80 1868   1   2     0        7
    ##         staff_hours    1828       40 1868  16  33     0       16
    ##            staffing       0     1868 1868   4   6     0        4
    ##    station_location       0     1868 1868  20  23     0      472
    ##        station_name       0     1868 1868   4  39     0      356
    ##             vending       0     1868 1868   2   3     0        2
    ## 
    ## ── Variable type:integer ────────────────────────────────────────────────────────────────
    ##  variable missing complete    n mean   sd p0 p25 p50 p75 p100     hist
    ##   route10    1845       23 1868 3    0     3   3   3   3    3 ▁▁▁▇▁▁▁▁
    ##   route11    1845       23 1868 7    0     7   7   7   7    7 ▁▁▁▇▁▁▁▁
    ##    route8    1820       48 1868 2.98 1.94  1   1   4   5    5 ▇▁▁▁▁▂▁▇
    ##    route9    1840       28 1868 2.54 1.17  2   2   2   2    5 ▇▁▁▁▁▁▁▂
    ## 
    ## ── Variable type:logical ────────────────────────────────────────────────────────────────
    ##        variable missing complete    n mean                      count
    ##             ada       0     1868 1868 0.25 FAL: 1400, TRU: 468, NA: 0
    ##           entry       0     1868 1868 0.94 TRU: 1753, FAL: 115, NA: 0
    ##  free_crossover       0     1868 1868 0.78 TRU: 1448, FAL: 420, NA: 0
    ## 
    ## ── Variable type:numeric ────────────────────────────────────────────────────────────────
    ##            variable missing complete    n   mean    sd     p0    p25
    ##   entrance_latitude       0     1868 1868  40.73 0.07   40.58  40.69
    ##  entrance_longitude       0     1868 1868 -73.86 3.42  -74.03 -73.99
    ##    station_latitude       0     1868 1868  40.73 0.07   40.58  40.69
    ##   station_longitude       0     1868 1868 -73.94 0.057 -74.03 -73.99
    ##     p50    p75   p100     hist
    ##   40.73  40.77  40.9  ▂▂▅▇▇▂▃▂
    ##  -73.96 -73.91  73.99 ▇▁▁▁▁▁▁▁
    ##   40.73  40.77  40.9  ▂▂▅▇▇▂▃▂
    ##  -73.96 -73.91 -73.76 ▃▇▅▃▂▁▁▁

``` r
## mutate(NYC_Subway_Data, entry = recode(entry, "YES" = TRUE, "NO" = FALSE))

## ifelse(NYC_Subway_Data$entry, "YES", "NO")
```

The `NYC_Subway_Data` dataset contains the following variables: line,
station, name, station latitude / longitude, route(s) served, entry,
vending, entrance type, and ADA compliance. Thus far I selected using
`select` for those previously mentioned variables and converted the
entry variable from a character to a logical variable. The dimensions
are 1,868 x 19. And these data are not yet tidy.

  - How many distinct stations are there? Note that stations are
    identified both by name and by line (e.g. 125th St A/B/C/D; 125st 1;
    125st 4/5); the distinct function may be useful here.

<!-- end list -->

``` r
distinct(NYC_Subway_Data, )
```

    ## # A tibble: 1,868 x 32
    ##   division line  station_name station_latitude station_longitu… route1
    ##   <chr>    <chr> <chr>                   <dbl>            <dbl> <chr> 
    ## 1 BMT      4 Av… 25th St                  40.7            -74.0 R     
    ## 2 BMT      4 Av… 25th St                  40.7            -74.0 R     
    ## 3 BMT      4 Av… 36th St                  40.7            -74.0 N     
    ## 4 BMT      4 Av… 36th St                  40.7            -74.0 N     
    ## 5 BMT      4 Av… 36th St                  40.7            -74.0 N     
    ## # ... with 1,863 more rows, and 26 more variables: route2 <chr>,
    ## #   route3 <chr>, route4 <chr>, route5 <chr>, route6 <chr>, route7 <chr>,
    ## #   route8 <int>, route9 <int>, route10 <int>, route11 <int>,
    ## #   entrance_type <chr>, entry <lgl>, exit_only <chr>, vending <chr>,
    ## #   staffing <chr>, staff_hours <chr>, ada <lgl>, ada_notes <chr>,
    ## #   free_crossover <lgl>, north_south_street <chr>,
    ## #   east_west_street <chr>, corner <chr>, entrance_latitude <dbl>,
    ## #   entrance_longitude <dbl>, station_location <chr>,
    ## #   entrance_location <chr>

  - How many stations are ADA compliant?

<!-- end list -->

``` r
sum(NYC_Subway_Data$ada, na.rm = TRUE)
```

    ## [1] 468

ANS: There are 468 ADA compliant stations.

  - What proportion of station entrances / exits without vending allow
    entrance?

<!-- end list -->

``` r
no_vending = filter(NYC_Subway_Data, vending == "NO")
yes_entry = filter(NYC_Subway_Data, entry == "TRUE")
```

## Problem 2

This problem uses the Mr. Trash Wheel dataset, available as an Excel
file on the course website. Please use the
HealthyHarborWaterWheelTotals2017-9-26.xlsx version.

Read and clean the Mr. Trash Wheel sheet

``` r
library(readxl)
MrTrashWheel_Data = read_excel("./Data/HealthyHarborWaterWheelTotals2018-7-28.xlsx")
MrTrashWheel_Data = janitor::clean_names(MrTrashWheel_Data)
head(MrTrashWheel_Data, 5)
```

    ## # A tibble: 5 x 15
    ##   dumpster month  year date                weight_tons volume_cubic_ya…
    ##      <dbl> <chr> <dbl> <dttm>                    <dbl>            <dbl>
    ## 1        1 May    2014 2014-05-16 00:00:00        4.31               18
    ## 2        2 May    2014 2014-05-16 00:00:00        2.74               13
    ## 3        3 May    2014 2014-05-16 00:00:00        3.45               15
    ## 4        4 May    2014 2014-05-17 00:00:00        3.1                15
    ## 5        5 May    2014 2014-05-17 00:00:00        4.06               18
    ## # ... with 9 more variables: plastic_bottles <dbl>, polystyrene <dbl>,
    ## #   cigarette_butts <dbl>, glass_bottles <dbl>, grocery_bags <dbl>,
    ## #   chip_bags <dbl>, sports_balls <dbl>, homes_powered <dbl>, x_1 <chr>

specify the sheet in the Excel file and to omit columns containing notes
(using the range argument and cell\_cols() function) use reasonable
variable names omit rows that do not include dumpster-specific data
rounds the number of sports balls to the nearest integer and converts
the result to an integer variable (using as.integer) Read and clean
precipitation data for 2016 and 2017. For each, omit rows without
precipitation data and add a variable year. Next, combine datasets and
convert month to a character variable (the variable month.name is built
into R and should be useful).

Write a paragraph about these data; you are encouraged to use inline R.
Be sure to note the number of observations in both resulting datasets,
and give examples of key variables. For available data, what was the
total precipitation in 2017? What was the median number of sports balls
in a dumpster in 2016?

## Problem 3

This problem uses the BRFSS data. DO NOT include this dataset in your
local data directory; instead, load the data from the p8105.datasets
package.

For this question:

format the data to use appropriate variable names; focus on the “Overall
Health” topic exclude variables for class, topic, question, sample size,
and everything from lower confidence limit to GeoLocation structure data
so that values for Response (“Excellent” to “Poor”) are column names /
variables which indicate the proportion of subjects with each response
(which are values of Data\_value in the original dataset) create a new
variable showing the proportion of responses that were “Excellent” or
“Very Good” Using this dataset, do or answer the following:

How many unique locations are included in the dataset? Is every state
represented? What state is observed the most? In 2002, what is the
median of the “Excellent” response value? Make a histogram of
“Excellent” response values in the year 2002. Make a scatterplot
showing the proportion of “Excellent” response values in New York County
and Queens County (both in NY State) in each year from 2002 to 2010.
